describe('kalatSi nivtis damateba', () => {
  it('add prodact and delete', () => {
    cy.visit('https://testzootopia.loremipsum.ge/ka')
    cy.get('.popmenu-burger > .burger-span > :nth-child(2)').click()
    cy.get('[imgsrc="/uploads/ProductCategory/335031597313845.png"] > [href="javascript:void(0)"]').click()
    cy.get('.cat-down.active > .category-holder > :nth-child(1) > .category-drop-title').click()
    cy.get('.category-holder > .active > :nth-child(2) > a').click()
    cy.get(':nth-child(1) > .price-cart > .product-cart').click()
    cy.get('.menu-pop > [href="https://testzootopia.loremipsum.ge/ka/cart"]').click()
    cy.get('.plus').click().click()
    cy.get('[href="https://testzootopia.loremipsum.ge/ka/product/1537-Bosch-HPC-PLUS-Adult-Ostrich-&-Potato-12,5-kg"] > h2').should('have.text','Bosch HPC PLUS Adult Ostrich & Potato 12,5 kg')
    cy.get('[for="gadaxda"]').click()
    cy.get('#own-delivery').click()
    cy.get('.cart-submit').click()
    cy.get(':nth-child(5) > .imail').type('tamzviadauri@gmail.com')
    cy.get('.ipass').type('123456')
    cy.get('.avtorization > .input-shablon > .form-button').click()
    cy.get('.input-div.alert > .alert > img').click()
  })
})